default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  pool: 5
 
development:
 <<: *default
  database: APPNAME_development

test:
 <<: *default
 database: APPNAME_test

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
  host: <%= ENV['HOSTNAME'] %>
  port: <%= ENV['PORT'] %>
  pool: 5
